## A. Arrays
NumPy arrays are basically just Python lists with added features. In fact, you can easily convert a Python list to a Numpy array using the np.array function, which takes in a Python list as its required argument. The function also has quite a few keyword arguments, but the main one to know is dtype. The dtype keyword argument takes in a NumPy type and manually casts the array to the specified type.

The code below is an example usage of np.array to create a 2-D matrix. Note that the array is manually cast to np.float32.

In [2]:
import numpy as np

arr = np.array([[0,1,2],[3,4,5]],dtype=np.float32)
print(arr)
print(repr(arr))

[[0. 1. 2.]
 [3. 4. 5.]]
array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


When the elements of a NumPy array are mixed types, then the array's type will be upcast to the highest level type. This means that if an array input has mixed int and float elements, all the integers will be cast to their floating-point equivalents. If an array is mixed with int, float, and string elements, everything is cast to strings.

The code below is an example of np.array upcasting. Both integers are cast to their floating-point equivalents

In [2]:
import numpy as np
arr1 = np.array([0,0.1,2])
print(repr(arr1))


array([0. , 0.1, 2. ])


## B.Copying
Similar to Python lists, when we make a reference to a NumPy array it doesn't create a different array. Therefore, if we change a value using the reference variable, it changes the original array as well. We get around this by using an array's inherent copy function. The function has no required arguments, and it returns the copied array.

In the code example below, c is a reference to a while d is a copy. Therefore, changing c leads to the same change in a, while changing d does not change the value of b.


In [3]:
a = np.array([0,1])
b = np.array([9,8])
c = a
print('Array :{}'.format(repr(a)))
c[0]=5;
print('Array:{}'.format(repr(a)))

d = b.copy()
d[0]=6;
print('Array:{}'.format(repr(b)))

Array :array([0, 1])
Array:array([5, 1])
Array:array([9, 8])


## C. Casting
We cast NumPy arrays through their inherent astype function. The function's required argument is the new type for the array. It returns the array cast to the new type.

The code below shows an example of casting using the astype function. The dtype property returns the type of an array.

In [6]:
arr2 = np.array([0,1,2]);
print(arr2.dtype);
arr2 = arr2.astype(np.float32);
print(arr2.dtype)

int64
float32


## D. NAN
When we don't want a NumPy array to contain a value at a particular index, we can use np.nan to act as a placeholder. A common usage for np.nan is as a filler value for incomplete data.

The code below shows an example usage of np.nan. Note that np.nan cannot take on an integer type.

In [3]:
arr3 = np.array([np.nan,1,1]);
print(repr(arr3));


arr3 = np.array([np.nan,'abc'])
print(repr(arr3));

np.array([np.nan,1,2],dtype=np.float32)
## - This is a numeric array with dtype=float32.

## np.array([np.nan,1,2],dtype=np.float32); if we didn't add this line:
# • 	Then it is a string array ( means Unicode string of up to 32 characters).
# • 	 here is literally the string , not a missing numerical value.
# • 	So the array contains text elements: "nan" & "abc"


array([nan,  1.,  1.])
array(['nan', 'abc'], dtype='<U32')


array([nan,  1.,  2.], dtype=float32)

  ## E.Infinity
  To represent infinity in NumPy, we use the np.inf special value. We can also represent negative infinity with -np.inf.

The code below shows an example usage of np.inf. Note that np.inf cannot take on an integer type.

In [6]:
print(np.inf>1000000);
# Checks if positive infinity is greater than 1,000,000 → prints True


arr4 = np.array([np.inf,5]);# Creates a NumPy array containing [∞, 5]
print(repr(arr4));# Prints the string representation of arr4 → 'array([inf, 5.])'

arr5 = np.array([-np.inf,1]);# Creates a NumPy array containing [-∞, 1]
print(repr(arr5));# Prints the string representation of arr5 → 'array([-inf,  1.])

# Will result in a OverflowError: If we uncomment line below and run again.
# np.array([np.inf, 3], dtype=np.int32)
# Trying to store positive infinity in a 32‑bit integer array → raises OverflowError because integers cannot represent infinity.

np.array([np.inf, 3], dtype=np.float32)
# Creates a NumPy array with dtype float32 → [∞, 3.0], which works because floating‑point types can represent ±∞.


True
array([inf,  5.])
array([-inf,   1.])


array([inf,  3.], dtype=float32)