## Indexing 
Explore indexing techniques in NumPy arrays, including direct access, slicing, and negative indexing. Learn to find minimum and maximum indices using np.argmin and np.argmax, applying these functions across specified axes. This lesson helps you manipulate and analyze data effectively with code exercises for practice.

### Chapter Goals:
- Learn about indexing arrays in NumPy
- Write code for indexing and slicing arrays
## A. Array accessing
Accessing NumPy arrays is identical to accessing Python lists. For multi-dimensional arrays, it is equivalent to accessing Python lists of lists.

The code below shows example accesses of NumPy arrays.

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[4])


arr = np.array([[6,3],[0,2]])

#subarray
print(arr[0][1])

1
5
3


## B. Slicing
NumPy arrays also support slicing. Similar to Python, we use the colon operator (i.e. arr[:]) for slicing. We can also use negative indexing to slice in the backwards direction.

The code below shows example slices of a 1-D NumPy array.

In [2]:
arr = np.array([1,2,3,4,5])
print(repr(arr[:]))      # full array → [1 2 3 4 5]
print(repr(arr[1:]))     # from index 1 to end → [2 3 4 5]
print(repr(arr[2:4]))    # from index 2 up to (not including) 4 → [3 4]
print(repr(arr[:-1]))    # all elements except last → [1 2 3 4]
print(repr(arr[-2:]))    # last two elements → [4 5]

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


For multi-dimensional arrays, we can use a comma to separate slices across each dimension.

The code below shows example slices of a 2-D NumPy array.

In [3]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(repr(arr[:]))        # full 2D array → all rows and columns
print(repr(arr[1:]))       # from row index 1 to end → [[4 5 6] [7 8 9]]
print(repr(arr[:,-1]))     # last column of all rows → [3 6 9]
print(repr(arr[:,1:]))     # all rows, columns from index 1 onward → [[2 3] [5 6] [8 9]]
print(repr(arr[0:1,1:]))   # first row only, columns from index 1 onward → [[2 3]]
print(repr(arr[0,1:]))     # first row flattened, columns from index 1 onward → [2 3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


### C. Argmin and argmax
In addition to accessing and slicing arrays, it is useful to figure out the actual indexes of the minimum and maximum elements. To do this, we use the np.argmin and np.argmax functions.

The code below shows example usages of np.argmin and np.argmax. Note that the index of element -6 is index 5 in the flattened version of arr.

In [5]:
arr = np.array([[-2,-1,-3],
                [4,5,-6],
                [-3,9,1]])

print((np.argmin(arr[0])))
print(np.argmax(arr[2]))
print(np.argmin(arr))

2
1
5


The np.argmin and np.argmax functions take the same arguments. The required argument is the input array and the axis keyword argument specifies which dimension to apply the operation on.

The code below shows how the axis keyword argument is used for these functions.


In [7]:
import numpy as np

# Maan lo ye 3-floor building hai jahan har floor par 3 rooms hain.
# Floor 0: [-2, -1, -3]
# Floor 1: [4, 5, 6]
# Floor 2: [-3, 9, 1]
arr = np.array([[-2, -1, -3],
                [4, 5, 6],
                [-3, 9, 1]])

# --- AXIS 0: 'STACK VIEW' (Vertical/Up-Down) ---
# Action: Lift mein baithe, har column ke liye upar se neeche (Floor 0 -> 1 -> 2) dekha.
# Logic: "Is column mein sabse chhota number kaunse Floor (index) par hai?"
# Crush: Floors (D) gayab ho gaye. Result mein 'Floor Index' mila.
print("Axis 0:", repr(np.argmin(arr, axis=0)))

# --- AXIS 1: 'ROW VIEW' (Horizontal/Left-Right) ---
# Action: Floor ke andar ghuse, har row mein left se right dekha.
# Logic: "Is row mein sabse chhota number kaunse Column (index) par hai?"
# Crush: Columns (N) gayab ho gaye. Result mein 'Column Index' mila.
print("Axis 1:", repr(np.argmin(arr, axis=1)))

# --- AXIS -1: 'LAST DIMENSION VIEW' (The End) ---
# Action: Hamesha sabse aakhri dimension (columns) ko target karta hai.
# Logic: 2D mein ye wahi karta hai jo Axis 1 karta hai (Column index return).
# Crush: Columns (N) gayab ho gaye. Result mein 'Column Index' mila.
print("Axis -1:", repr(np.argmin(arr, axis=-1)))

Axis 0: array([2, 0, 0])
Axis 1: array([2, 0, 0])
Axis -1: array([2, 0, 0])
