## Numpy Basics
Explore the fundamental NumPy operations to create and manipulate arrays effectively. Understand how to generate ranged data with arange and linspace, reshape and flatten arrays, transpose dimensions, and create arrays filled with zeros or ones. This lesson equips you with practical skills to handle multidimensional data for machine learning projects

## A.Ranged Data
While np.array can be used to create any array, it is equivalent to hardcoding an array. This won't work when the array has hundreds of values. Instead, NumPy provides an option to create ranged data arrays using np.arange. The function acts very similar to the range function in Python, and will always return a 1-D array.

The code below contains example usages of np.arange.

In [1]:
import numpy as np

arr = np.arange(5)
print(repr(arr))
# Creates integers from 0 to 4 → prints 'array([0, 1, 2, 3, 4])'

arr2 = np.arange(5.1)
print(repr(arr2))
# Creates integers from 0 up to 5 (since 5.1 is float, it stops before 5.1) → prints 'array([0., 1., 2., 3., 4., 5.])'

arr3 = np.arange(-1, 4)
print(repr(arr3))
# Creates integers from -1 up to 3 → prints 'array([-1, 0, 1, 2, 3])'

arr = np.arange(-1.5, 4, 2)
print(repr(arr))
# Creates numbers starting at -1.5, step 2, until <4 → prints 'array([-1.5, 0.5, 2.5])'

arr = np.arange(0, 1, 0.1)
print(repr(arr))
# Creates numbers from 0 to <1 with step 0.1 → prints 'array([0. , 0.1, 0.2, ..., 0.9])'

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])


The output of np.arange is specified as follows:

If only a single number, n, is passed in as an argument, np.arange will return an array with all the integers in the range [0, n). Note: the lower end is inclusive while the upper end is exclusive.

For two arguments, m and n, np.arange will return an array with all the integers in the range [m, n).

For three arguments, m, n, and s, np.arange will return an array with the integers in the range [m, n) using a step size of s.

Like np.array, np.arange performs upcasting. It also has the dtype keyword argument to manually cast the array.

To specify the number of elements in the returned array, rather than the step size, we can use the np.linspace function.

This function takes in a required first two arguments, for the start and end of the range, respectively. The end of the range is inclusive for np.linspace, unless the keyword argument endpoint is set to False. To specify the number of elements, we set the num keyword argument (its default value is 50).

The code below shows example usages of np.linspace. It also takes in the dtype keyword argument for manual casting.

In [ ]:
arr = np.linspace(5,11,num=5);
print(repr(arr))
# Generates 5 evenly spaced values between 5 and 11 inclusive → prints 'array([ 5. , 6.5, 8. , 9.5, 11. ])'

arr = np.linspace(5,11,num=4,endpoint=False);
print(repr(arr));
# Generates 4 evenly spaced values between 5 (inclusive) and 11 (exclusive) → prints 'array([5. , 6.5, 8. , 9.5])'

arr = np.linspace(5,4,num=4,dtype=np.int32)
print(repr(arr))#
#- you forced dtype=np.int32, the fractional values get truncated to integers.

array([ 5. ,  6.5,  8. ,  9.5, 11. ])
array([5. , 6.5, 8. , 9.5])
array([5, 4, 4, 4], dtype=int32)


# B.Reshaping Data
The function we use to reshape data in NumPy is np.reshape. It takes in an array and a new shape as required arguments. The new shape must exactly contain all the elements from the input array. For example, we could reshape an array with 12 elements to (4, 3), but we can't reshape it to (4, 4).

We are allowed to use the special value of -1 in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array.

The code below shows example usages of np.reshape.


In [35]:
arr = np.arange(8);
print(arr);

reshaped_arr = np.reshape(arr,(2,4));
print(repr(reshaped_arr));
# Reshapes the existing array into a 2×4 matrix → prints the new 2D array
print('New Shape:{}'.format(reshaped_arr.shape))
# Prints the shape of the reshaped array → 'New Shape:(2, 4)'

reshaped_arr = np.reshape(arr,(-1,2,2));
# Reshapes the array into a 3D shape where NumPy infers the first dimension (here -1) → prints the new 3D array
print(repr(reshaped_arr));
print('New Shape:{}'.format(reshaped_arr.shape))
# Prints the shape of the reshaped array → 'New Shape:(?, 2, 2)' where ? is inferred (depends on arr’s length)


[0 1 2 3 4 5 6 7]
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New Shape:(2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New Shape:(2, 2, 2)


In [36]:
import numpy as np

# Question you asked:
# "If I put (-1,3,2) then..? What if the array has only 8 elements?"

arr = np.arange(8)

# My explanation:
# NumPy will raise a ValueError because 8 elements cannot be reshaped into (-1,3,2).
# The known dimensions (3*2=6) do not evenly divide 8, so the missing dimension (-1) cannot be inferred.

try:
    reshaped = np.reshape(arr, (-1, 3, 2))
    print(reshaped)
except ValueError as e:
    print("Error:", e)


Error: cannot reshape array of size 8 into shape (3,2)


While the np.reshape function can perform any reshaping utilities we need, NumPy provides an inherent function for flattening an array. Flattening an array reshapes it into a 1D array. Since we need to flatten data quite often, it is a useful function.
The code below flattens an array using the inherent flatten function.

In [3]:
arr = np.arange(8);
arr = np.reshape(arr,(2,4));
flattened = arr.flatten();
print(repr(arr));
print('arr shape:{}'.format(arr.shape))
print(repr(flattened));
print('Flattened Shape:{}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape:(2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
Flattened Shape:(8,)


## C. Transposing
Similar to how it is common to reshape data, it is also common to transpose data. Perhaps we have data that's supposed to be in a particular format, but some new data we get is rearranged. We can just transpose the data, using the np.transpose function, to convert it to the proper format.

The code below shows an example usage of the np.transpose function. The matrix rows become columns after the transpose

In [6]:
arr = np.arange(8);
arr = np.reshape(arr,(4,2));
transposed = np.transpose(arr);
print(repr(arr));
print('arr Shape:{}'.format(arr.shape));
print(repr(transposed));
print('transposed shape:{}',format(transposed.shape))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr Shape:(4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape:{} (2, 4)


Yes, np.transpose does convert the reshaped data, but it always follows the mathematical transpose rule (swap rows ↔ columns). If you want a specific format (like rearranging elements differently), you’d use other functions like reshape, ravel, or slicing — not transpose.


The function takes in a required first argument, which will be the array we want to transpose. It also has a single keyword argument called axes, which represents the new permutation of the dimensions.

The permutation is a tuple/list of integers, with the same length as the number of dimensions in the array. It tells us where to switch up the dimensions. For example, if the permutation had 3 at index 1, it means the old third dimension of the data becomes the new second dimension (since index 1 represents the second dimension).
The code below shows an example usage of the np.transpose function with the axes keyword argument. The shape property gives us the shape of an array

In [ ]:
arr = np.arange(24);
arr = np.reshape(arr,(3,4,2));
print(repr(arr))
transposed = np.transpose(arr,axes=(1,2,0));
print('arr shape:{}'.format(arr.shape));
print('transposed shape:{}'.format(transposed.shape))
print(repr(transposed))


## the numbers (3,4,2) are not steps — they are the dimensions (shape) of the new array.
# Breaking it down:
# - 3 → the size of axis 0 (think of it as 3 blocks).
# - 4 → the size of axis 1 (each block has 4 rows).
# - 2 → the size of axis 2 (each row has 2 columns).
# So the array is structured like this:
# 3 blocks × 4 rows × 2 columns = 24 elements total.


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])
arr shape:(3, 4, 2)
transposed shape:(4, 2, 3)
array([[[ 0,  8, 16],
        [ 1,  9, 17]],

       [[ 2, 10, 18],
        [ 3, 11, 19]],

       [[ 4, 12, 20],
        [ 5, 13, 21]],

       [[ 6, 14, 22],
        [ 7, 15, 23]]])


## D. Zeros and ones
Sometimes, we need to create arrays filled solely with 0 or 1. For example, since binary data is labeled with 0 and 1, we may need to create dummy datasets of strictly one label. For creating these arrays, NumPy provides the functions np.zeros and np.ones. They both take in the same arguments, which includes just one required argument, the array shape. The functions also allow for manual casting using the dtype keyword argument.

The code below shows example usages of np.zeros and np.ones.

In [15]:
arr = np.zeros(4);
print(repr(arr));


arr = np.ones((2,3));
print(repr(arr));

arr = np.ones((2,3), dtype=np.int32);
print(repr(arr));

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


If we want to create an array of 0's or 1's with the same shape as another array, we can use np.zeros_like and np.ones_like.

The code below shows example usages of np.zeros_like and np.ones_like.

In [18]:
arr = np.array([[1,2],[3,4]]);
print(repr(np.zeros_like(arr)));

arr = np.array([[0.,1.],[1.2,4.]]);
print(repr(np.ones_like(arr)));
print(repr(np.ones_like(arr,dtype= np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)
