## Random
Explore how to apply random operations in NumPy including generating random integers, sampling from uniform and normal distributions, custom probability sampling, and in-place shuffling of arrays. This lesson helps you understand and write code using the np.random submodule to manipulate data effectively for machine learning tasks.

## A. Random integers#
Similar to the Python random module, NumPy has its own submodule for pseudo-random number generation called np.random. It provides all the necessary randomized operations and extends it to multi-dimensional arrays. To generate pseudo-random integers, we use the np.random.randint function.

The code below shows example usages of np.random.randint.

In [2]:
import numpy as np
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5,high=6))
# - np.random.randint(low, high) → generates a random integer in the range [low, high).
# - Here, low = 5 and high = 6.
# - That means the only possible integer is 5, because the range includes 5 but excludes 6.


random_arr = np.random.randint(-3,high=14,size=(2,2));
# # Create a 2x2 array with random integers between -3 and 13

print(repr(random_arr))

3
3
5
array([[ 0, 13],
       [ 1, 11]], dtype=int32)


The np.random.randint function takes in a single required argument, which actually depends on the high keyword argument. If high=None (which is the default value), then the required argument represents the upper (exclusive) end of the range, with the lower end being 0. Specifically, if the required argument is n, then the random integer is chosen uniformly from the range [0, n).

If high is not None, then the required argument will represent the lower (inclusive) end of the range, while high represents the upper (exclusive) end.

The size keyword argument specifies the size of the output array, where each integer in the array is randomly drawn from the specified range. As a default, np.random.randint returns a single integer.

## B. Utility functions
Some fundamental utility functions from the np.random module are np.random.seed and np.random.shuffle. We use the np.random.seed function to set the random seed, which allows us to control the outputs of the pseudo-random functions. The function takes in a single integer as an argument, representing the random seed.

The code below uses np.random.seed with the same random seed. Note how the outputs of the random functions in each subsequent run are identical when we set the same random seed.

In [4]:
np.random.seed(1);
print(np.random.randint(10));
random_arr = np.random.randint(3,high=100,size=(2,2));

print(repr(random_arr));

#New Seed
np.random.seed(2);
print(np.random.randint(10));
random_arr2 = np.random.randint(3,high=100,size=(2,2));
print(repr(random_arr2))

#Original seed
np.random.seed(1);
print(np.random.randint(10));
# random_arr3 = np.random.randint(10)
random_arr3=np.random.randint(3,high=100,size=(2,2));
print(repr(random_arr3))

5
array([[15, 75],
       [12, 78]], dtype=int32)
8
array([[18, 75],
       [25, 46]], dtype=int32)
5
array([[15, 75],
       [12, 78]], dtype=int32)


Computers cannot generate truly random numbers; they generate "pseudo-random" numbers based on a complex mathematical formula. If you start that formula from the exact same point, you will get the exact same sequence of "random" numbers every single time.

### The Analogy
Imagine you have a deck of cards.

- Without a seed: You shuffle the deck randomly. Every time you play, the order of the cards is different.

- With a seed: You have a special "shuffling machine." If you set the machine to setting 1, it will always shuffle the cards in the exact same order because it follows a pre-defined path.

In [11]:
import numpy as np

# 1. Set the seed to 42
np.random.seed(42)
print("Run 1:", np.random.randint(0, 10, 3))
# Output: Run 1: [6 3 7]

# 2. Reset the seed to 42 again
np.random.seed(42)
print("Run 2:", np.random.randint(0, 10, 3))
# Output: Run 2: [6 3 7]

# 3. If you don't reset the seed, you get a new part of the sequence
print("Run 3 (continued):", np.random.randint(0, 10, 3))
# Output: Run 3 (continued): [4 6 9]

Run 1: [6 3 7]
Run 2: [6 3 7]
Run 3 (continued): [4 6 9]


------------------------------------------------------------------------------

The np.random.shuffle function allows us to randomly shuffle an array. Note that the shuffling happens in place (i.e. no return value), and shuffling multi-dimensional arrays only shuffles the first dimension.

The code below shows example usages of np.random.shuffle. Note that only the rows of matrix are shuffled (i.e. shuffling along first dimension only)
The rule that it only shuffles the first dimension means that if you have a matrix (2D array), it treats the "rows" as the units to be shuffled, but it does not mix up the individual elements within those rows.

In [17]:
vec = np.array([1,2,3,4,5]);
np.random.shuffle(vec);
print(repr(vec));
np.random.shuffle(vec);
print(repr(vec));


matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]]);

np.random.shuffle(matrix)
print(repr(matrix))

array([4, 3, 5, 1, 2])
array([4, 3, 2, 5, 1])
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])


## C. Distributions
Using np.random we can also draw samples from probability distributions. For example, we can use np.random.uniform to draw pseudo-random real numbers from a uniform distribution.

The code below shows usages of np.random.uniform.




In [19]:
print(np.random.uniform());
print(np.random.uniform(low=-1.5,high=2.2))
print(repr(np.random.uniform(size=3)));
print(repr(np.random.uniform(low=-3.4,high=5.9,size=(2,2))));


0.9394989415641891
1.8108611965823007
array([0.59789998, 0.92187424, 0.0884925 ])
array([[-1.57735938, -2.97938621],
       [-0.37442792,  0.21469879]])


The function np.random.uniform actually has no required arguments. The keyword arguments, low and high, represent the inclusive lower end and exclusive upper end from which to draw random samples. Since they have default values of 0.0 and 1.0, respectively, the default outputs of np.random.uniform come from the range [0.0, 1.0).

The size keyword argument is the same as the one for np.random.randint, i.e. it represents the output size of the array.

Another popular distribution we can sample from is the normal (Gaussian) distribution. The function we use is np.random.normal.

The code below shows usages of np.random.normal.

In [22]:
print(np.random.normal());
# Draw one random number from a normal distribution with mean=0 and std=1 (the default)
 
print(np.random.normal(loc=1.5,scale=3.5));
# Draw one random number from a normal distribution with mean=1.5 and std=3.5

print(repr(np.random.normal(loc=-2.4,scale=4.0,size=(2,2))))
# Draw a 2x2 matrix of random numbers from a normal distribution with mean=-2.4 and std=4.0


0.5821227947130392
4.607119608576751
array([[ 1.17732932,  0.61999119],
       [-3.22866356, -4.89390958]])


- Normal distribution (also called Gaussian distribution) is the famous “bell curve.”
- loc → the mean (center of the distribution).
- scale → the standard deviation (spread of the distribution).
- size → the shape of the output (how many random numbers you want)


In [24]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

data = np.random.normal(loc=0, scale=1, size=1000)
plt.hist(data, bins=30, density=True, edgecolor='black')

x = np.linspace(-4, 4, 200)
pdf = norm.pdf(x, loc=0, scale=1)
plt.plot(x, pdf, 'r', label="Theoretical PDF")

plt.title("Normal Distribution")
plt.xlabel("Value")
plt.ylabel("Density")
plt.legend()
plt.show()


ModuleNotFoundError: No module named 'matplotlib'

## D. Custom sampling
While NumPy provides built-in distributions to sample from, we can also sample from a custom distribution with the np.random.choice function.

The code below shows example usages of np.random.choice.

In [ ]:
colors = ['red','blue','green'];
print(np.random.choice(colors));
print(repr(np.random.choice(colors,size=(2))))
print(repr(np.random.choice(colors,size=(2,2),
                            p=[0.8,0.19,0.01])));



red
array(['blue', 'blue'], dtype='<U5')
array([['red', 'blue'],
       ['red', 'red']], dtype='<U5')


In [56]:
arr = np.arange(1,6);
print(repr(arr))

array([1, 2, 3, 4, 5])
